### ISSUE TITLE
Introduce a local storage/preferences/settings plugin

### ISSUE THREAD

**Issue by heytherewill** [MvvmCross/MvvmCross-Plugins#100]
Is it interesting to have a plugin to store simple Key/Value pairs using `NSUserDefaults`/ `ISharedPreferences`/`IsolatedStorageSettings` on iOS/Android/Windows Phone?

It could be similar to [James Montemagno's](https://github.com/jamesmontemagno/Xamarin.Plugins/tree/master/Settings), but also having an index that allows getting and setting string values:

```
public string this[string key]
{
    get
    {
        return Get(key);
    }
    set 
    {
        if (value != null)
        {
            Set(key, value);
        }
        else
        {
            Remove(key);
        }
    }
}
```

I use such plugin in most of my projects, so I can easily code this one up if it's interesting for the community :)

**Comment by Cheesebaron** [comment]
I have one as well specifically for MvvmCross. I can't see why another one would help at all.
