### ISSUE TITLE
Bootstrap files do not get created for Windows UWP app

### ISSUE THREAD

**Issue by jaeger25** [MvvmCross/MvvmCross-Plugins#113]
To help us fix your issue, please provide the information in the below template. 

https://github.com/EvaRichie/MySimpleMvvmCross
See https://github.com/MvvmCross/MvvmCross/issues/1255, which looks like it was closed for some reason
1. Create PCL project and windows UWP app project and install MvvmCross nuget packages
2. Attempt to add MvvmCross.Plugins.Visibility to the projects
### Expected behavior

There should be a Bootstrap folder with a bootstrap file for the visibility plugin in the UWP project
### Actual behavior

No Bootstrap folder or files
### Configuration

**Version:** 4.1.6

**Platform:** Windows UWP

**Comment by jaeger25** [comment]
Looks like this may actually be an issue with nuget 3.0 not copying Content dir anymore: https://docs.nuget.org/create/uwp-create

**Comment by martijn00** [comment]
This should be fixed in newer Nuget versions.
