### ISSUE TITLE
MvvmCross-Plugins/ResxLocalization/ needs an explaination!

### ISSUE THREAD

**Issue by halitsavafoglu** [MvvmCross/MvvmCross-Plugins#122]
### Steps to reproduce
1. Create a new Xamarin PCL project.
2. Applying MvvmCross standard on this project.
3. ResxLocalization plugin installed.
### Expected behavior

There should be an explanation for this plugin.
### Actual behavior

I can't apply this functionality.. all references are from 2013 and it's plugins are no longer supported!
### Configuration

**Version:** VS2015 / Xamarin Forms 2.3 / MVVMCross 4.2

**Platform:** iOS/Android/WPF/Windows Store/Windows Phone Store/Windows UWP

**Comment by lothrop** [comment]
I added more information to https://mvvmcross.com/v4.2/docs/resxlocalization but the basic information was already there. The reference from 2013 is still relevant and supported.
