### ISSUE TITLE
ResourceLoader plugin doesn't pull in File plugin from nuget

### ISSUE THREAD

**Issue by JasonBSteele** [MvvmCross/MvvmCross-Plugins#13]
I added the ResourceLoader plugin to my Core, Droid and Touch projects.
I added code to FirstViewModel to read a text file using GetTextResource
However this only worked for Droid. For Touch I got an error saying that the File plugin could not be found. I added the File plugin to Touch and it started working.

I used the current stable nuget packages v3.5.1.

**Comment by martijn00** [comment]
As the readme describes you need a filestore to use this on some platforms: https://github.com/MvvmCross/MvvmCross-Plugins/blob/master/ResourceLoader/Readme.md

It might be an idea to include the File plugin by default on iOS into the nuspec.
