### ISSUE TITLE
SQLitePCL crash on Android 7

### ISSUE THREAD

**Issue by erviem99** [MvvmCross/MvvmCross-Plugins#135]
Are there any requirements for using the new MvvmCross SQLitePCL Plugin on Android 7 other than including the Nuget packages?

My app will run fine on real devices below API level 24, but in the Android 7 emulator it crashes immediately on startup with an java.lang.UnsatisfiedLinkError: "couldn't find "libmonodroid.so".

The same app would just show a toast on Android 7 prior to migrating to the new Plugin about linking native libraries.

I target platform 23 when linking (from Visual Studio 2015 with the latest stable Xamarin).

**Comment by Cheesebaron** [comment]
Are you using SharedRuntime and a Debug build or what are you attempting?

**Comment by erviem99** [comment]
Problem solved. I didn't link my app for the x86_64 architecture, and for some reason it would still deploy (but it crashed on launch). After adding both armeabi-v7a and x86 it work on both the emulator and my phone. Sorry about that.
