### ISSUE TITLE
MvvmCross.Plugins.Email.Droid apparently gets stripped out when enabling full linking (SDK and User assemblies)

### ISSUE THREAD

**Issue by mfkl** [MvvmCross/MvvmCross-Plugins#15]
`mvx:Diagnostic:  2.53 Loading plugin assembly: Cirrious.MvvmCross.Plugins.Email.Droid.dll
10-07 17:26:49.942 I/mono-stdout( 3351): mvx:Diagnostic:  2.53 Loading plugin assembly: Cirrious.MvvmCross.Plugins.Email.Droid.dll
[0:] mvx:Diagnostic:  2.53 Loading plugin assembly: Cirrious.MvvmCross.Plugins.Email.Droid.dll
10-07 17:26:49.992 D/Mono    ( 3351): Assembly Loader probing location: '/Users/builder/data/lanes/2058/58099c53/source/monodroid/builds/install/mono-armv7/lib/Cirrious.MvvmCross.Plugins.Email.Droid.dll'.
An unhandled exception occured.`

This is all I get, crash at startup when loading assemblies. When setting the linker to SDK only it seems to work fine.

Has anybody encountered this before?

Using 3.5.1 and latest stable releases from the Xamarin platform.

**Comment by Cheesebaron** [comment]
Please open a new issue if this is still an issue. Closing as it is stale.
