### ISSUE TITLE
Null reference exception following readme steps

### ISSUE THREAD

**Issue by PereAlmendro** [MvvmCross/MvvmCross-Plugins#152]
### Steps to reproduce

1.  `private readonly IMvxSqliteConnectionFactory _sqliteConnectionFactory;`
2.  `SQLiteConnection dbCon;`
3. `dbCon = _sqliteConnectionFactory.GetConnection("dbname");`

### Expected behavior
connect /set database

### Actual behavior
Object reference not set to an instance of an object.
Null reference exception at point 3.

### Configuration
mvvmcross 4.4.0
database file extension .db3
**Version:** 4.4

**Platform:** iOS/Android/WPF/Windows Store/Windows Phone Store/Windows UWP

**Comment by Cheesebaron** [comment]
What exception?
Where is the stack trace?

**Comment by PereAlmendro** [comment]
I did `new SQLiteConnection(x,y) ` and had same issue so I believe that the problem is not in this plugin. -.- sorry for making loose your time. I get confused as getconnection method returns a new SQLiteConnection(). Furthermore I cant send stacktrace as I have IOS in a place and Win10 at home and with win10 i cant debug due to the downloadCache plugin I believe. but the problem i'm getting is telling me that  _sqliteConnectionFactory is null, like im making a new over a null object. Well dont want to take more time from you sorry just a strange thing is happening on my project .
