### ISSUE TITLE
MvxFileStore FullPath Customization

### ISSUE THREAD

**Issue by danieleardissone** [MvvmCross/MvvmCross-Plugins#154]
Hello,
in MVVMCross 3.5 I was able to customize the FullPath property of MvxFileStore with a different path instead of the default one; I created my implementation of that class and overrided that property.
Something like this:

`internal class CustomMvxAndroidFileStore : MvxFileStore
{
    private Context _context;

    private Context Context
    {
        get
        {
            if (_context == null)
            {
                _context = Mvx.Resolve<IMvxAndroidGlobals>().ApplicationContext;
            }
            return _context;
        }
    }

    protected override string FullPath(string path)
    {
        return Path.Combine(Context.FilesDir.Path, path);
    }
}`

Now in MVVMCross 4 MvxFileStore doesn't exist anymore.
In my Android project I tried to create a custom class like I did in MVVMCross 3.5; I extended MvxAndroidFileStore and implemented IMvxFileStore interface instead of MvxFileStore, then I injected this new class during Setup. Every time I resolve this class it's not my version (CustomMvxAndroidFileStore) like I expect, but it's the standard MvxAndroidFileStore.
It seems like I am forced to use default MvxAndroidFileStore.
Is it right?

So, how can I change the default save path of the MVVMCross File Plugin?
Thank you.

**Comment by Cheesebaron** [comment]
Please open this in the main repository :)
