### ISSUE TITLE
Commits got lost on new Plugins Repository

### ISSUE THREAD

**Issue by IlSocio** [MvvmCross/MvvmCross-Plugins#17]
This commit on DownloadCache plugin:
https://github.com/MvvmCross/MvvmCross/pull/1087
seems to got lost when the plugins have been moved to the new repository:

New repo version: https://github.com/MvvmCross/MvvmCross-Plugins/blob/master/DownloadCache/MvvmCross.Plugins.DownloadCache.Droid/MvxAndroidImage.cs

Fixed version: https://github.com/IlSocio/MvvmCross/blob/06fad8e946c83ebd0ebabc45d156b4954e4296f0/Plugins/Cirrious/DownloadCache/Cirrious.MvvmCross.Plugins.DownloadCache.Droid/MvxAndroidImage.cs

Maybe other commits got lost too... Is there a way to check that all plugins have the latest commits?

**Comment by martijn00** [comment]
Good catch! I am not sure if i could check if more commits are lost, but i'll look into this.

**Comment by martijn00** [comment]
Fixed in https://github.com/MvvmCross/MvvmCross-Plugins/pull/18
