### ISSUE TITLE
DownloadCache Plugin (beta4) not always loading image in Android

### ISSUE THREAD

**Issue by xleon** [MvvmCross/MvvmCross-Plugins#19]
I´m using version 4 beta 4 for all the nuggets (but I think this was happening in beta-3 as well)
When I use Json Plugin (required to persist files, right?) I get no errors in the output but the image just doesn´t get loaded some times...
Run the app => image loads ok
Run again => it doesn´t load
Run again => it loads
Run again => it doesn´t load
and so on... same thing in the same sequence 

This just happens in Android. In iOS is working perfectly:

Get this repo to reproduce the error: https://github.com/xleon/DownloadCacheIssue

**Just a note:**
If I remove Json plugin from the Android project, the image will always load, but then I loose persistence mechanism...

**Comment by Cheesebaron** [comment]
Which plugins do you have installed?
Which bootstrap files do you have?
How do you use the DownloadCache?

**Comment by xleon** [comment]
I´m creating a new clean project just to reproduce the error. Give me a few minutes and I´ll post it

**Comment by xleon** [comment]
https://github.com/xleon/DownloadCacheIssue

To answer your questions:
1. DownloadCache, File, Json
2. DownloadCache, File, Json
3. I don´t use it directly, just there in the project to get persistent file cache with [MvxImageView](https://github.com/xleon/DownloadCacheIssue/blob/master/DownloadCacheIssueTest/Resources/layout/FirstView.axml#L7)

**Comment by Cheesebaron** [comment]
Hmm OK. That is pretty odd.

I really hate that DownloadCache plugin, it is complicated :(

**Comment by xleon** [comment]
Anyway I´ll take a look at the code to see if I can help. Any tips are welcome

**Comment by xleon** [comment]
Is there anyway to disable the cache functionality without removing the Json plugin?
I´m in the situation that I can´t remove the Json plugin because AppCompat and Fragging depends on it

**Comment by Cheesebaron** [comment]
Seems like this fixed it: https://github.com/MvvmCross/MvvmCross/commit/d7733f2fc65b36502f59052bce1bf824948f38b9

**Comment by Cheesebaron** [comment]
Until next release you can just have your own MvxImageView in your own project which has this fix.

**Comment by xleon** [comment]
Yeah, I tried that and it definitely works now. Thanks

**Comment by xleon** [comment]
BTW, this change has fixed other problems with MvxImageView. I´m using this component in a MvxListView with the source (ImageUrl) binding to a custom converter. In this case it´s just loading bundle files, not externals. For any reason the image was failing randomly to load on the first/second row of the list. After the fix everything works as it should

**Comment by cyrilcathala** [comment]
I also had some bugs with the DownloadCache, the fix seems to work it but... why?!

Another way to fix it is to constrain the Post(...) call and insure it doesn't stack when called multiple times. Here is my implementation:

``` csharp
        private Bitmap _image;
        private int _isPostPlanned;

        private void ImageHelperOnImageChanged(object sender, MvxValueEventArgs<Bitmap> mvxValueEventArgs)
        {
            // Catch the given image
            _image = mvxValueEventArgs.Value;

            // Only call the Post method when no other call is stacked
            if (_isPostPlanned == 0)
            {
                Interlocked.Increment(ref _isPostPlanned);

                Post(() =>
                {
                    // marshal back on UI Thread
                    Interlocked.Decrement(ref _isPostPlanned);

                    try
                    {
                        SetImageBitmap(_image);
                    }
                    catch (Exception ex)
                    {
                        Mvx.Error(ex.Message);
                    }
                });
            }
        }
```
