### ISSUE TITLE
Dependency resolve failed for ResourceLoader plugin

### ISSUE THREAD

**Issue by FatCow8686** [MvvmCross/MvvmCross-Plugins#20]
I am using MvvmCross 4.0.0 beta-4, and try to add ResourceLoader plugin for my iOS project but it is not added with the following error shown in the console:

Adding MvvmCross.HotTuna.Plugin.ResourceLoader...
Attempting to resolve dependency 'MvvmCross.HotTuna.CrossCore (≥ 4.0.0-beta4)'.
Attempting to resolve dependency 'MvvmCross.HotTuna.Binding (≥ 4.0.0-beta4)'.
Attempting to resolve dependency 'MvvmCross.Plugins.File (≥ 4.0.0-beta4)'.
Unable to resolve dependency 'MvvmCross.Plugins.File (≥ 4.0.0-beta4)'.

Please help to fix the issue, thanks =)

**Comment by martijn00** [comment]
Thanks for notifying. This is a bug in the nuspec: https://github.com/MvvmCross/MvvmCross-Plugins/blob/master/nuspec/MvvmCross.HotTuna.Plugin.ResourceLoader.nuspec#L37

**Comment by martijn00** [comment]
Fixed in: https://github.com/MvvmCross/MvvmCross-Plugins/commit/10d47bbc86d61fa37cb7b52e7fd0bb25572f171b
