### ISSUE TITLE
SQLitePCL plugin does not work on iOS.

### ISSUE THREAD

**Issue by jokvist** [MvvmCross/MvvmCross-Plugins#22]
I'm using beta 5 of SQLitePCL Plugin.  This works fine on Android, but not on iOS.
When doing: 
`factory.GetConnection("database.db");`
I get:

> Cirrious.CrossCore.Exceptions.MvxIoCResolveException: Failed to construct DataService

And I also see this in the build output: 

> Could not find `SQLite.Net.Platform.XamarinIOS` referenced by assembly `MvvmCross.Plugins.Sqlite.Touch, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null`.

Don't know if that has something to do with it...

**Comment by jokvist** [comment]
Workaround:
Reference SQLite.Net.Platform.XamarinIOS.dll from plugin source manually, since NuGet package `SQLite.Net.Async-PCL` adds `SQLite.Net.Platform.XamarinIOS.Unified` and not `SQLite.Net.Platform.XamarinIOS`.

So maybe this is specific to Unified iOS projects.

BTW: `SQLite.Net.Async-PCL` does not get installed automatically when installing this plugin (it is not a dependency...). Are there a reason for that?

**Comment by Cheesebaron** [comment]
The problem is that the Nuspec for the plugin is missing a dependency on SQLite.Net-PCL.

Thanks for reporting this :+1:

**Comment by jokvist** [comment]
Thanks! But I think the workaround still needs to be done in iOS unified projects...
Because this error is seen after manually installing those packages. See my second post where I explains the filename issue in Unified project.
