### ISSUE TITLE
Is SqlLite published on Nuget?

### ISSUE THREAD

**Issue by ghost** [MvvmCross/MvvmCross-Plugins#36]

**Comment by Cheesebaron** [comment]
Yes

**Comment by ghost** [comment]
The readme fails to explain how to install the sqlite plugin. The docs on the main repo are outdated for it.

**Comment by Cheesebaron** [comment]
There are docs in the readme here: https://github.com/MvvmCross/MvvmCross-Plugins/tree/master/SQLite-PCL

You should just install MvvmCross.HotTuna.Plugin.SQLitePCL from NuGet.

Although I think there is an issue with the SQLite.Net-PCL NuGet the latest version is compiled against.

https://github.com/MvvmCross/MvvmCross-Plugins/issues/22

**Comment by ghost** [comment]
I see, would be nice if that was in the readme. BTW the whole HotTuna thing is funny but unneccessary.

**Comment by Cheesebaron** [comment]
Tell @slodge that :smile:

We can unfortunately not rename the nuget package id's. However, we could look into making some without the HotTuna part and tell people to switch.

**Comment by ghost** [comment]
@slodge HotTuna is confusing becuase I searched on Nuget using the namespace of this plugin, which should have worked. It doesn't because it's HotTuna.

Same goes for Cirrious. I guess the solution is to create new packages with proper ids and deprecate the old ones, remember to update the docs too.

**Comment by bspinner** [comment]
Wouldn't be the first time Mvx does this for a major release... Could be done another (last) time.

**Comment by ghost** [comment]
@Cheesebaron @martijn00 @slodge perfect timing to stop all of that for a v4 release.

Makes upgrading to major releases a real PITA too.

**Comment by Cheesebaron** [comment]
That is a nice idea. Please add all issues of that nature here: https://github.com/MvvmCross/MvvmCross/issues/1190
