### ISSUE TITLE
DownloadCache iOS reuse cell "flickering" images in 4.0.0-beta7

### ISSUE THREAD

**Issue by ghostiam** [MvvmCross/MvvmCross-Plugins#37]
Hello. In version 3.5.1 it works well, but in version 4.0.0-beta7 I see a problem with the "flickering" images in a table cell.

![downloadcache3 5 1](https://cloud.githubusercontent.com/assets/12181586/11763577/a3867582-a14b-11e5-87ca-1ffbfc68dab5.gif) ![downloadcache4 0 0](https://cloud.githubusercontent.com/assets/12181586/11763578/a46ed1b0-a14b-11e5-85ee-2177133745f0.gif)

**Comment by Cheesebaron** [comment]
Yes I see it too, also sometimes reused cells show old picture.

**Comment by ghostiam** [comment]
Experimentally it has been ascertained that the problem is not in DownloadCache.

**Comment by alexshikov** [comment]
@GhostRussia Why do you think it's not in DownloadCache?
I assume it's there, and related to await/async usage. My guess is we need to introduce CancellationToken, so that if the new ImageUrl set, then we cancel any processing tasks inside MvxDynamicImageHelper

**Comment by ghostiam** [comment]
@SeeD-Seifer I have added to the project source code DownloadCache version 4.0.0-beta7 and compiled it with the libraries of version 3.5.1 and everything works well. 
I think the problem in ImageLoader, but I'm not sure. Unfortunately I can not find the code responsible for the cancellation downloads images in the old versions.

**Comment by alexshikov** [comment]
Just a status check: has anybody investigated the issue?

**Comment by martijn00** [comment]
I didn't hear about anyone investigating this.

**Comment by ghostiam** [comment]
SeeD-Seifer, thank you for the solution of the problem.
