### ISSUE TITLE
Duplicated source file in FilePlugin implementation + mismatch between WindowsStore and WindowsPhone

### ISSUE THREAD

**Issue by IlSocio** [MvvmCross/MvvmCross-Plugins#52]
As my understanding the:
https://github.com/MvvmCross/MvvmCross-Plugins/blob/master/File/MvvmCross.Plugins.File.WindowsStore/MvxWindowsStoreFileStore.cs

Should be removed and replaced with the:
https://github.com/MvvmCross/MvvmCross-Plugins/blob/master/File/MvvmCross.Plugins.File.WindowsCommon/MvxWindowsCommonFileStore.cs

Furthermore, the MvxWindwosStoreFileStore.cs seems to to contain a Bug because it references the "Name" property instead on the "Path"
https://github.com/MvvmCross/MvvmCross-Plugins/blob/master/File/MvvmCross.Plugins.File.WindowsStore/MvxWindowsStoreFileStore.cs#L185

**Comment by martijn00** [comment]
Can you open a PR for this?

**Comment by IlSocio** [comment]
Unfortunately, I have very few time currently and my environment is not configured for working with github... so it will take time.
I just noticed the issue for a file plugin I'm working on right now and thought it would be nice to report it here to keep track of the issue.
