### ISSUE TITLE
Location plugin: Error handling is missing for iOS

### ISSUE THREAD

**Issue by iducool** [MvvmCross/MvvmCross-Plugins#53]
I use location plugin and we found that it is not handling errors. I have looked into code so, I found that it is in To do list :)
Could you add error handling in location plugin?

**Comment by g0rdan** [comment]
Hi guys! I made some improvements, but it's not full.
I can't find description of kCLErrorDomain error codes. I determined some values in practice, but i can't find all of them. One more issue. I don't find the way, how i can check MonitoringFailed method.
I'm newbie. Can i just send pull request to master? Or i should make something else?

**Comment by Cheesebaron** [comment]
You can find the error codes here: https://developer.apple.com/library/mac/documentation/CoreLocation/Reference/CoreLocationConstantsRef/#//apple_ref/c/tdef/CLError

When you want something added to the plugin, just make a pull request

**Comment by Cheesebaron** [comment]
This should be addressed by 59d33a4
