### ISSUE TITLE
SQLitePCL not working on IOS in xamarin.forms application

### ISSUE THREAD

**Issue by krajniak** [MvvmCross/MvvmCross-Plugins#58]
I'm using MvvmCross.Plugin.SQLitePCL version 4.0.0.0-beta8
It works fine on droid project.
When I'm trying to run IOS on first attempt of using connection instance I'm getting:

> Could not load file or assembly 'SQLite.Net.Platform.XamarinIOS, Version=3.1.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.

**Comment by Cheesebaron** [comment]
This is most likely related to: https://github.com/MvvmCross/MvvmCross-Plugins/commit/3fd7ddd55dcb686cc05aa595aaa0c84cc8cb9bae#diff-a0b27e4004b7829f50260b7a11045736

Either wait or build it from source.

**Comment by krajniak** [comment]
As a workaround, you can add the missing reference in iOS project, the needed dll is in lib folder
