### ISSUE TITLE
Issue with MvxImageView

### ISSUE THREAD

**Issue by chamamo** [MvvmCross/MvvmCross-Plugins#61]
Hi,

On android I'm using MvxRecyclerView with MvxImageView in each item.

Some times I have this issue;

System.InvalidOperationExceptionCollection was modified; enumeration operation may not execute.
System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)throwhelper.cs:94
System.Collections.Generic.Dictionary<TKey, TValue>.ValueCollection.Enumerator.MoveNext()dictionary.cs:1105
System.Linq.Enumerable.WhereSelectEnumerableIterator<TSource, TResult>.MoveNext()Enumerable.cs:282
System.Linq.Enumerable.Sum(IEnumerable<_> source)Enumerable.cs:1289
System.Linq.Enumerable.Sum<TSource>(IEnumerable<_> source, Func<_,_> selector)Enumerable.cs:1374
MvvmCross.Plugins.DownloadCache.MvxImageCache<T>.<ReduceSizeIfNecessary>b__7_0()
Cirrious.CrossCore.Core.MvxLockableObjectHelpers.RunSyncOrAsyncWithLock(object lockObject, Action action, Action whenComplete)
Cirrious.CrossCore.Core.MvxAllThreadDispatchingObject.RunSyncOrAsyncWithLock(Action action, Action whenComplete)
MvvmCross.Plugins.DownloadCache.MvxImageCache<T>.ReduceSizeIfNecessary()
MvvmCross.Plugins.DownloadCache.MvxImageCache<T>.<>c__DisplayClass6_0.<RequestImage>b__0()
System.Threading.Tasks.Task.InnerInvoke()Task.cs:2901
System.Threading.Tasks.Task.Execute()Task.cs:2523

Thank you in advance

**Comment by alexshikov** [comment]
This is the same issue as https://github.com/MvvmCross/MvvmCross-Plugins/issues/31

**Comment by Cheesebaron** [comment]
Closing this one, please continue in #31
