### ISSUE TITLE
MethodBinding and FieldBinding plugin does not install correctly in UWP project

### ISSUE THREAD

**Issue by CherechesC** [MvvmCross/MvvmCross-Plugins#67]
To help us fix your issue, please provide the information in the below template. 
Adding MvvmCross.Plugin.MethodBinding or MvvmCroos.Plugin.FieldBinding to an UWP project will make the project to fail to compile.

> Note: There is often little we can do without a minimal reproducible sample of the issue, so please provide that in a **standalone git repository** and link it here.

https://github.com/Chery/UWPMvxMethodBindingError
### Steps to reproduce
1. Create UWP project
2. Add MvvmCross.Plugin.MethodBinding pluging (or MvvmCross.Plugin.FieldBinding)
3. Try to rebuild the project
### Expected behavior

Tell us what should happen
The project builds.
### Actual behavior

Tell us what happens instead
The project fails to build because of the following error:
Cannot resolve Assembly or Windows Metadata file 'MvvmCross.Binding.dll'
### Configuration

**Version:** 4.0.0

**Platform:** Windows UWP

**Comment by Cheesebaron** [comment]
Tried adding the MvvmCross.Bindings NuGet manually?

**Comment by CherechesC** [comment]
@Cheesebaron I am kind of new to working with Nuget. Can you please elaborate on what you mean by adding it manually? I did edit the project.json file and added the dependency for MvvmCross.Binding, but that does not fix the issue. As far as I saw, there is no UAP target in the nuspec file for MethodBinding and FieldBinding. Could this cause the issue?

**Comment by Cheesebaron** [comment]
It should pick the one from the lib\dotnet folder in the NuGet, so the nuspec is ok for UWP/UAP
