### ISSUE TITLE
Implement IsConnected property in Network Plugin

### ISSUE THREAD

**Issue by keozx** [MvvmCross/MvvmCross-Plugins#70]
### Steps to reproduce
1. Well there is not IsConnected property, @aritchie has one in his repo which I modified a bit but it's not being updated: https://github.com/aritchie/acrmvvmcross/blob/master/Acr.MvvmCross.Plugins.Network/INetworkService.cs 
### Expected behavior

When accessing the IsConnected you can tell if the device is actually connected to Internet instead of using IsHostReachable
### Actual behavior

idem
### Configuration

**Version:** 4.0.0

**Platform:** iOS/Android/WPF/Windows Store/Windows Phone Store/Windows UWP

So, I wonder if the Network plugin shall have this behavior or not, and if yes I would like this piece to be integrated into the plugin, I think is very useful to have connectivity state access and goes well with the purpose of the plugin, I'm not sure why hasn't been implemented though. 

I can help with integrating the code from aritchie with minor modifications and implementations for all mobile platforms but I wonder if we have to ask him or just tell in comments it is code from his mostly :)

Thanks

**Comment by Cheesebaron** [comment]
https://github.com/Cheesebaron/Cheesebaron.MvxPlugins/tree/master/Connectivity

I have a plugin that works. Otherwise there is always the one @JamesMontemagno has which can easily be wrapped in a MvvmCross plugin.

**Comment by keozx** [comment]
Ah that's true! didn't had that in the radar, thanks!
