### ISSUE TITLE
Read from stream during deserialization

### ISSUE THREAD

**Issue by Giorgi** [MvvmCross/MvvmCross-Plugins#71]
To help us fix your issue, please provide the information in the below template. 

MvxJsonRestClient reads the whole response stream in memory as string. [This can cause unnecessary memory allocations.](http://www.newtonsoft.com/json/help/html/performance.htm) See code at: https://github.com/MvvmCross/MvvmCross-Plugins/blob/master/Network/MvvmCross.Plugins.Network/Rest/MvxJsonRestClient.cs#L27
### Steps to reproduce
1. Make request with MvxJsonRestClient
### Expected behavior

It should read directly from stream during deserialization
### Actual behavior

MvxJsonRestClient reads the whole stream in memory.
### Configuration

**Version:** 4.0.0

**Platform:** iOS/Android/WPF/Windows Store/Windows Phone Store/Windows UWP

**Comment by Cheesebaron** [comment]
We would need to extend https://github.com/MvvmCross/MvvmCross-Plugins/blob/master/Json/MvvmCross.Plugins.Json/MvxJsonConverter.cs to allow deserializing streams.
And extend this interface to reflect that: https://github.com/MvvmCross/MvvmCross/blob/4.0/MvvmCross/Platform/Platform/Platform/IMvxTextSerializer.cs

Json.Net can do that with something like this:

```
var serializer = new JsonSerializer();

using (var sr = new StreamReader(stream))
using (var jsonTextReader = new JsonTextReader(sr))
{
    return serializer.Deserialize(jsonTextReader);
}
```
