### ISSUE TITLE
Download Cache Plugin Does Not Have Dependency For System.Collections.Immutable Nuget Package

### ISSUE THREAD

**Issue by SharpMobileCode** [MvvmCross/MvvmCross-Plugins#78]
On an iOS application we're using the MvxImageLoader to load images into UIImageView controls.  When we upgraded to Mvvmcross 4.1, we noticed that our images were no longer loading and defaulted to the ErrorImage.  Upon further inspection, it appears that the IMvxImageCache was failing to resolve here:

https://github.com/MvvmCross/MvvmCross-Plugins/blob/93a82fce924b0a058e3fd55bbf2b4e3aaf3e061e/DownloadCache/MvvmCross.Plugins.DownloadCache/MvxDynamicImageHelper.cs#L135

In addition, we also noticed we received a warning in the Application Output Window that the DLL System.Collections.Immutable could not be found.  So, we added v1.1.37 of [System.Collections.Immutable](https://www.nuget.org/packages/System.Collections.Immutable/) from Nuget and this resolved our issue.

In addition, our Android App would not compile until we added the same Nuget Package into our Android project.  

I'm guessing that the [nuspec](https://github.com/MvvmCross/MvvmCross-Plugins/blob/master/nuspec/MvvmCross.Plugin.DownloadCache.nuspec) needs to be updated to include a dependency for the System.Collections.Immutable Nuget Package.
### Configuration

**Version:** 4.1.0

**Platform:** iOS/Android/

**Comment by Cheesebaron** [comment]
You are right. I guess I forgot to add it yesterday :) Thanks!

**Comment by ghost** [comment]
When updating to v4.1.1 I got the following error:

> Could not install package 'System.Resources.ResourceManager 4.0.0'. You are trying to install this package into a project that targets 'Xamarin.iOS,Version=v1.0', but the package does not contain any assembly references or content files that are compatible with that framework.

Manually adding v1.1.36 and sticking to v4.1.0 worked though.

**Comment by Cheesebaron** [comment]
4.1.7 of the plugin does not have this issue.

**Comment by NielsWillems** [comment]
Cheers

**Comment by promontis** [comment]
@Cheesebaron This isn't pushed to nuget yet right?

**Comment by Cheesebaron** [comment]
It is in the stuff on nuget.
