### ISSUE TITLE
Where is an actual source code of MvvmCross.HotTuna.Plugin.SQLitePCL?

### ISSUE THREAD

**Issue by xperiandri** [MvvmCross/MvvmCross-Plugins#8]
Where is an actual source code of MvvmCross.HotTuna.Plugin.SQLitePCL?

I cloned this repository opened solution - assembly names different, namespaces different.
How?

I need to extend functionality but can't find where is the source code!!!

**Comment by martijn00** [comment]
Don't swear.

The plugin is here: https://github.com/MvvmCross/MvvmCross-Plugins/tree/master/SQLite-PCL

**Comment by xperiandri** [comment]
I see that it is there.
It is does not correspond to that was posted on NuGet!

So I do changes I want, swap binaries and it does not work.
*Namespaces does not correspond.
*Assembly names does not correspond.
*Runtime exception - cannot find plugin module.

**Comment by xperiandri** [comment]
@martijn00 could you contact to Author to update repository?
It is impossible not to keep repository up to date!
I lost 3 days, first one for searching where is the correct repository, last two for trying to make this sources produce binaries similar to the binaries in a MvvmCross.HotTuna.Plugin.SQLitePCL package.

**Comment by Cheesebaron** [comment]
I can't fathom that you have spent 3 days searching for the source and producing binaries.

Lets say you were going to have to do this again, what would have helped you finding it?

**Comment by xperiandri** [comment]
If repository contains sources for more than one NuGet package and especially if it is so confusing as in this repository where are two folders containing SQLite sources than NuGet package property "Project URL" must contain deep link into sources folder.

@Cheesebaron, so where are the actual sources from which `MvvmCross - Sqlite PCL Plugin 4.0.0-beta3` was produced?

**Comment by Cheesebaron** [comment]
We are phasing out the other SQLite plugins, so in the future there will only be one (just like Highlander). There was a mistake in the Nuspec which points at the SQLite version instead of SQLite-PCL. I will look at that today.

**Comment by xperiandri** [comment]
OK, you updated repository.
But current sources and `MvvmCross - Sqlite PCL Plugin 4.0.0-beta3` don't have too much in common.

My question is: **How to do a quick change to `MvvmCross - Sqlite PCL Plugin 4.0.0-beta3` so I can swap binaries in `packages\MvvmCross.HotTuna.Plugin.Sqlite.4.0.0-alpha3\lib` with my modified version?**

**Comment by Cheesebaron** [comment]
> But current sources and MvvmCross - Sqlite PCL Plugin 4.0.0-beta3 don't have too much in common.

What do you mean? There is only the PCL 4.0.0-beta3 and 4.0.0-beta4 now. The other have been unlisted.

To swap just uninstall the old package.

**Comment by xperiandri** [comment]
I mean what I exactly said

Let's compare
<img width="463" alt="mvvmcross-plugins-sqlite repository" src="https://cloud.githubusercontent.com/assets/2365592/9855499/3af3a172-5b17-11e5-9a50-8f73a83f84d8.png">
This is `MvvmCross.Plugins.SQLite` solution opened from the latest commit
<img width="912" alt="mvvmcross-plugins-sqlite" src="https://cloud.githubusercontent.com/assets/2365592/9855520/60f4c9fa-5b17-11e5-9a0f-28e4a20ceb31.png">

And this is a content of `MvvmCross - Sqlite PCL Plugin 4.0.0-beta3`
<img width="296" alt="mvvmcross 4 beta 3 sqlite namespaces" src="https://cloud.githubusercontent.com/assets/2365592/9855543/8f451364-5b17-11e5-9813-d256d62415a1.png">

**Do you see differences in assembly names and namespaces?**

And there is no dependency on `SQLite.Net-PCL`
<img width="484" alt="mvvmcross 4 beta 3" src="https://cloud.githubusercontent.com/assets/2365592/9855554/aa2deb1a-5b17-11e5-8067-2808bdfdac5b.png">
**So the sources in repository and sources from which `MvvmCross - Sqlite PCL Plugin 4.0.0-beta3` was produced are different!**

**Comment by Cheesebaron** [comment]
The namespace of the SQLitePCL is the same as the old SQLite plugin.
