### ISSUE TITLE
Investigate changes in SQLite on Android N

### ISSUE THREAD

**Issue by martijn00** [MvvmCross/MvvmCross-Plugins#81]
I am not sure if you are aware, but there are a lot of changes coming in Android N that will effect all sorts of apps. The largest change that effects libraries that you have a dependency on will be SQLite. I haven't looked into the the implementation, but I am assuming that it is relying on the built in SQlite.so in Android itself. Starting with Android N apps can no longer use system native libraries and must embed their own libraries such as sqlite.so. 

This should be relatively easy to fix if you aren't doing this today. Be sure to read the Android N changes: https://developer.android.com/preview/behavior-changes.html#ndk

CC: @jamesmontemagno @Cheesebaron @Redth @garuma

**Comment by Cheesebaron** [comment]
Xamarin does not have any support for Android N, so can't debug or deploy from VS or XS to an AVD or device running Android N.

Filed a bug report here: https://bugzilla.xamarin.com/show_bug.cgi?id=39964

**Comment by leye0** [comment]
As of today we can deploy on N. There is this nice article about the usage of SQLite on N. http://ericsink.com/entries/sqlite_android_n.html

**Comment by Cheesebaron** [comment]
We've switched to sqlite-net-pcl which uses sqlite-net-pcl.raw which works on Android N.
