### ISSUE TITLE
Allow to use FusedLocationProvider as Android plugin

### ISSUE THREAD

**Issue by alexshikov** [MvvmCross/MvvmCross-Plugins#84]
**Request:** Provide option to use FusedLocationProviderApi as location service on Android.

**Existing implementation:** https://github.com/MvvmCross/MvvmCross/pull/1134

**Concerns:**
- Currently implemented as another plugin. Because, it have to use the same namespace (due to bootstrap specific) it is impossible to use both plugins.
- If the device does not have **Google Play Services**, then FusedLocationProviderApi won't work (the old plugin will)

**Thoughts:**
- Inject new implementation into old plugin with support of configuration file, which provide what implementations should be used (**Old**, **Fused**, **Any**).

NOTE: FusedLocationProvider depends on GooglePlayServices NuGet packages.

Do you think it is a good idea to keep both implementations in the same plugin? Or there should be a new plugin?

**Comment by martijn00** [comment]
I think this should be a new one. Because in the nuspec we should define a dependency on GooglePlayServices, and we wouldn't want to do that with the old plugin.

**Comment by thefex** [comment]
Please CC me when repository starts. I have a lot of experience with Fused Location API, I can help.

**Comment by thefex** [comment]
Concerns:
If the device does not have Google Play Services then FusedLocationProviderApi won't work (the old plugin will) - no. FusedLocationAPI gives ability to notify user about errors + it can navigate user to store and download/update Google Play Services.
Besides that: current Plugin architecture isn't good enough to expose all Fused API functionallity. It should be rewritten.

**Comment by alexshikov** [comment]
@thefex could you please review the existing implementation then? This is a PR to 3.5.x https://github.com/MvvmCross/MvvmCross/pull/1134 (I was going to adapt it to 4.x)

**Comment by martijn00** [comment]
Maybe we could open a new branch with the original PR, so you can both work on it?

**Comment by alexshikov** [comment]
I'll prepare a PR.

**Comment by thefex** [comment]
Ok guys - give an exact link of which implementation I should take care of. Will look at that on Saturday

**Comment by alexshikov** [comment]
@thefex Please, check PR #86

**Comment by martijn00** [comment]
I think this is fixed now @SeeD-Seifer ?

**Comment by alexshikov** [comment]
@martijn00 it can be closed, right.
