### ISSUE TITLE
Network plugin should use tasks instead of callbacks

### ISSUE THREAD

**Issue by Giorgi** [MvvmCross/MvvmCross-Plugins#85]
Rest client methods should return `task` instead of taking callbacks as parameter. This will make the plugin async/await friendly.

**Platform:** iOS/Android/WPF/Windows Store/Windows Phone Store/Windows UWP

**Comment by martijn00** [comment]
Can you make a PR to fix this?

**Comment by Giorgi** [comment]
I can if I have some free time in next few days.

**Comment by Giorgi** [comment]
I also want to convert it to HttpClient so that I can keep ability to cancel the request but it will be difficult to test that the converted version works correctly. Any suggestions how can we test it?

**Comment by Giorgi** [comment]
@martijn00 Can you review the PR I made?

**Comment by martijn00** [comment]
As for me it looks fine, but as you already pointed out this is breaking. How does @Cheesebaron feel about this?

**Comment by Giorgi** [comment]
This is now merged.
