### ISSUE TITLE
Adding File and DownloadCache plugin leads to compile error in android project

### ISSUE THREAD

**Issue by musyokamuthangya** [MvvmCross/MvvmCross-Plugins#90]
Severity    Code    Description Project File    Line    Suppression State
Error       Exception while loading assemblies: System.IO.FileNotFoundException: Could not load assembly 'System.Collections.Immutable, Version=1.1.37.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Perhaps it doesn't exist in the Mono for Android profile?
File name: 'System.Collections.Immutable.dll'
   at Xamarin.Android.Tuner.DirectoryAssemblyResolver.Resolve(AssemblyNameReference reference, ReaderParameters parameters)
   at Xamarin.Android.Tasks.ResolveAssemblies.AddAssemblyReferences(ICollection`1 assemblies, AssemblyDefinition assembly, Boolean topLevel)
   at Xamarin.Android.Tasks.ResolveAssemblies.Execute()

**Comment by Cheesebaron** [comment]
Thanks for filing this issue.

To get it working add the System.Collections.Immutable NuGet. Reason the dependency was removed is because it won't install in iOS projects, because the profile that NuGet is using is not supported.

**Comment by musyokamuthangya** [comment]
Thanks. Will do that tomorrow and close the issue.

Thanks again

**Comment by musyokamuthangya** [comment]
Resolved the above issue but app crashes when deployed.

MvvmCross.Platform.Plugins.MvxFilePluginManager.FindPlugin (System.Type toLoad) - Could not find plugin type in assembly

[MvxFilePluginManager.cs](https://github.com/MvvmCross/MvvmCross/blob/4.0/MvvmCross/Platform/Platform/Plugins/MvxFilePluginManager.cs#L50)

**Comment by musyokamuthangya** [comment]
Resolved above as well, it was the linker stripping away necessary code

**Comment by domedellolio** [comment]
Thanks guys you did my day!

**Comment by LIST2** [comment]
Hello (hope someone still has an eye on this thread),
I've been running into the same (above described) problem using Mvvmcross V4.2.2

My test project (based on example https://www.youtube.com/watch?v=e-ZKgO8fTw4&list=PLR6WI6W1JdeYSXLbm58jwAKYT7RQR31-W&index=3) compiled and run just fine with following NuGet packages loaded:
package id="MvvmCross" version="4.2.3" targetFramework="monoandroid60"
package id="MvvmCross.Binding" version="4.2.3" targetFramework="monoandroid60"
package id="MvvmCross.Core" version="4.2.3" targetFramework="monoandroid60"
package id="MvvmCross.Platform" version="4.2.3" targetFramework="monoandroid60"
package id="MvvmCross.Plugin.File" version="4.2.3" targetFramework="monoandroid60"

After I added MvvmCross.Plugin.DownloadCache (coming with dependent Xamarin.Android.Support.v4 package) I get the following build error:
- ...error : Exception while loading assemblies: System.IO.FileNotFoundException: Could not load assembly 'System.Collections.Immutable, Version=1.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Perhaps it doesn't exist in the Mono for Android profile?
- ...error : Dateiname: "System.Collections.Immutable.dll"
- ...error :    bei Xamarin.Android.Tuner.DirectoryAssemblyResolver.Resolve(AssemblyNameReference reference, ReaderParameters parameters)
- ...error :    bei Xamarin.Android.Tasks.ResolveAssemblies.AddAssemblyReferences(ICollection`1 assemblies, AssemblyDefinition assembly, Boolean topLevel)
- ...error :    bei Xamarin.Android.Tasks.ResolveAssemblies.Execute()

Unfortunately adding NuGet package System.Collections.Immutable doesn't help.
Now I even got 26 errors:
- ...ThingsView.Droid\obj\Debug\android\src\mono\android\support\v4\app\FragmentManager_OnBackStackChangedListenerImplementor.java(8,41): javac.exe error :  error: package android.support.v4.app.FragmentManager does not exist
- ...ThingsView.Droid\obj\Debug\android\src\mono\android\support\v4\app\FragmentManager_OnBackStackChangedListenerImplementor.java(8,41): javac.exe error :         android.support.v4.app.FragmentManager.OnBackStackChangedListener
- ...ThingsView.Droid\obj\Debug\android\src\mono\android\support\v4\app\FragmentManager_OnBackStackChangedListenerImplementor.java(8,41): javac.exe error : 
- ...ThingsView.Droid\obj\Debug\android\src\mono\android\support\v4\content\Loader_OnLoadCanceledListenerImplementor.java(8,36): javac.exe error :  error: package android.support.v4.content.Loader does not exist
- ...ThingsView.Droid\obj\Debug\android\src\mono\android\support\v4\content\Loader_OnLoadCanceledListenerImplementor.java(8,36): javac.exe error :      android.support.v4.content.Loader.OnLoadCanceledListener
- ...and many more (all related to \mono\android\support\v4..)

I must say that I'm new to mobile development and especially to Xamarin and Mvvmcross.
I appreciate every hint to overcome this issue.

Tanks in advance.

**Comment by LIST2** [comment]
Packages have been cut out of my previous post...
package id="MvvmCross" version="4.2.3" targetFramework="monoandroid60"
package id="MvvmCross.Binding" version="4.2.3" targetFramework="monoandroid60"
package id="MvvmCross.Core" version="4.2.3" targetFramework="monoandroid60"
package id="MvvmCross.Platform" version="4.2.3" targetFramework="monoandroid60"
package id="MvvmCross.Plugin.File" version="4.2.3" targetFramework="monoandroid60"
