### ISSUE TITLE
Figure out System.Collection.Immutable dependency on iOS

### ISSUE THREAD

**Issue by Cheesebaron** [MvvmCross/MvvmCross-Plugins#91]
If you try adding the System.Collections.Immutable NuGet to an iOS project, you get a nice message telling you that `System.Resources.ResourceManager` does not have a target for Xamarin.iOS and the installation fails.

I suggest that we either implement our own immutable list or take the one from Mono: https://github.com/mono/ImmutableCollections/blob/master/System.Collections.Immutable/System.Collections.Immutable/ImmutableList.cs or Corefx: https://github.com/dotnet/corefx/blob/master/src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableList.cs
#90

**Comment by PelleRavn** [comment]
I haven't had the problem with adding System.Collections.Immutable from Nuget on any of our machines.
But I think it would be a good idea not to be depended on System.Collections.Immutable for the DownloadCache plugin.

**Comment by Cheesebaron** [comment]
I can't add it in Visual Studio in a iOS project.

**Comment by PelleRavn** [comment]
Is there anything stopping us for copying the ImmutableList file to the MvvmCross project? The license should of course stay there. Don't know if it conflicts with the license MvvmCross is distributed as.

**Comment by ericsink** [comment]
In my case, this problem was "fixed" by installing version 1.1.36 (not the latest) of the nuget package for System.Collections.Immutable.

It looks like 1.1.37 switched to the new "dotnet" style dependencies.

**Comment by jamsoft** [comment]
Installing 1.1.36 in iOS worked for me.

**Comment by voydz** [comment]
For me the latest DownloadCache Plugin depends upon `System.Collection.Immutable >= 1.1.37` downgrading is no real option unfortunately.

**Comment by SlyNet** [comment]
Same with Mono. Nuget fails with error message
`Could not install package 'System.Resources.ResourceManager 4.0.0'. You are trying to install this package into a project that targets 'MonoAndroid,Version=v5.1'`

**Comment by GnoZ** [comment]
Same as @SlyNet with MonoAndroid,Version=v6.0

**Comment by martijn00** [comment]
Fixed in https://github.com/MvvmCross/MvvmCross-Plugins/pull/106
