### ISSUE TITLE
Bootstrapper for PictureChooser can't resolve .iOS.Plugin

### ISSUE THREAD

**Issue by PelleRavn** [MvvmCross/MvvmCross-Plugins#92]
### Steps to reproduce
1. Download PictureChooser Plugin for a Mvx project
2. Build all projects
### Expected behavior

Build without any build issues
### Actual behavior

The file with PictureChooserPluginBootstrap tells it can't resolve 'MvvmCross.Plugins.PictureChooser.**iOS.Plugin**'.

> PictureChooserPluginBootstrap.cs: Error CS0234: The type or namespace name `iOS' does not exist in the namespace`MvvmCross.Plugins.PictureChooser'. Are you missing an assembly reference? (CS0234)
### Configuration

**Version:** MvvmCross 4.1.0. PictureChooser 4.2.0

**Platform:** iOS

**Comment by Cheesebaron** [comment]
Thanks for reporting this issue.

This should be fixed in 4.2.1 for some reason the dll wasn't published in the nuget.
