### ISSUE TITLE
Missing change in Download cache plugin

### ISSUE THREAD

**Issue by mierzynskim** [MvvmCross/MvvmCross-Plugins#95]
While updating Download cache plugin from 3.5 to 4.1.1, I noticed that something strange happened to **MvxFileDownloadCache** class.
You can compare:
- current version https://github.com/MvvmCross/MvvmCross-Plugins/blob/master/DownloadCache/MvvmCross.Plugins.DownloadCache/MvxFileDownloadCache.cs
- 3.5.\* version https://github.com/MvvmCross/MvvmCross-Plugins/blob/41270db4fd281b205488dc1d372f0454ad17c275/Cirrious/DownloadCache/Cirrious.MvvmCross.Plugins.DownloadCache/MvxFileDownloadCache.cs

My commit (https://github.com/MvvmCross/MvvmCross-Plugins/commit/41270db4fd281b205488dc1d372f0454ad17c275) is missing. It fixed the issue related to disappearing images from cache and I'm still experiencing it if I use 4.1.1 version.

Any ideas / explanation why did it happen?

**Comment by martijn00** [comment]
Hmm not sure why it is gone, but if you could make a new PR to add this again, we could merge it.

**Comment by mierzynskim** [comment]
Ok I made a new PR #96
